// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yctvqfonfotoawjdyqss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljdHZxZm9uZm90b2F3amR5cXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDA4NDksImV4cCI6MjA2MzY3Njg0OX0.uiSdm4FJ4iqI4voFr9XBePZg2K9jIQMMkNiAetY97UA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);